### ISSUE TITLE
Supervision policy callback doesn't get the message that was being processed at the time of crash

### ISSUE THREAD

**Issue by yawaramin** [ncthbrt/reason-nact#7]
In the documentation ( https://nact.io/lesson/reasonml/supervision ), it is mentioned that

> A custom supervision policy is a function which takes in the exception which was thrown, the message which was being processed at the time at which the fault occurred, and the context of the parent.

However, in the `Nact.rei` interface, the supervision policy type is defined as

```reason
type supervisionPolicy('msg, 'parentMsg) =
  (exn, supervisionCtx('msg, 'parentMsg)) => Js.Promise.t(supervisionAction);
```

It looks like this callback will not get the message that was processed at time of crash. It would be really great to get that message in this callback function, because that would let me send back a meaningful error response from the supervision policy handler back to the calling actor.

You could introduce the message in a backwards-compatible way, as an optional parameter:

```reason
type supervisionPolicy('msg, 'parentMsg) =
  (~msg: 'msg=?, exn, supervisionCtx('msg, 'parentMsg)) => Js.Promise.t(supervisionAction);
```

**Comment by ncthbrt** [comment]
The tricky thing is that the parent doesn't know the message type of the faulted child. 
Thus 'msg` is the type of the parent message. It may instead be better to define the supervision policy on the child instead, this may require changes to the js implementation as well, but that is fine if that is what it takes.  If you can think of an alternative avenue of typing the supervision policy, I'd love to hear it. My experience with ML is such that I might be missing an obvious approach

**Comment by ncthbrt** [comment]
@yawaramin I've discussed it with colleagues, and they agree that you have a good point 👍. 
In the next few days I'll modify the code to have the supervision policy specified on the child instead of the parent.

**Comment by yawaramin** [comment]
Supervision policy specified by the child itself is a good idea. It makes it possible for a top-level actor (i.e. a direct child of the actor system) to be supervised also. I haven't looked too much into Nact internals but this decoupled supervision approach will definitely be better. But I'll look through the internals a bit more and get back to you if anything stands out.

**Comment by ncthbrt** [comment]
@yawaramin v2.0.0 of ReasonNact is out and as promised allows you to specify the supervision policy on the child.

**Comment by yawaramin** [comment]
Amazing! I can't wait to try this out on my project :-)

**Comment by yawaramin** [comment]
https://github.com/ncthbrt/reason-nact/commit/146a40a8da4bb4006a33e51d078ca3f09a355731

**Comment by yawaramin** [comment]
Tried it out, works like a charm! I'll post some more details soon.
